version: "3"
services:
  hub:
    image: selenium/hub:4.16
    #ports:
    #- 4444:4444 --> dont need this as it is for us if we want to open the browser to see the progress and access the hub
  chrome:
    image: selenium/node-chrome:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
     replicas: 0 # no. of containers
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1 #to disable password asked at VN session password: secret
  firefox:
    image: selenium/node-firefox:4.16
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
     replicas: 0
    environment:
    - SE_EVENT_BUS_HOST=hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    - SE_NODE_MAX_SESSIONS=4
    - SE_VNC_NO_PASSWORD=1 #to disable password asked at VN session password: secret